version: '3.8'

services:
  # This service builds and runs your Flask backend
  backend:
    build: ./First Attempt/backend
    ports:
      - "5000:5000"
    volumes:
      - ./First Attempt/backend:/app
    environment:
      - ZAP_API_KEY=${ZAP_API_KEY}
      - ZAP_HOST=zap
      - ZAP_PORT=8080
    depends_on:
      - zap

  # This service pulls and runs the ZAP daemon
  zap:
    image: owasp/zap2docker-stable:2.14.0
    ports:
      - "8080:8080"
    command: ["zap.sh", "-daemon", "-port", "8080", "-host", "0.0.0.0", "-config", "api.key=t9zmbgqgmhup8prnbg21bt"]
