# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend code
COPY . .

# Expose the port Flask runs on
EXPOSE 5000

# Set the command to run your Flask application
CMD ["flask", "run", "--host=0.0.0.0"]
